name: e_services_beta
description: e-services Beta.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  path_provider: ^2.1.0
  permission_handler: ^11.0.1
  open_filex: ^4.3.2
  
  

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1   # <--- AJOUTÃ‰

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Configuration du package flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/e_Services.png"
  min_sdk_android: 21